#ifndef FLOWCONTROL_GLOBAL_H
#define FLOWCONTROL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FLOWCONTROL_LIBRARY)
#  define FLOWCONTROLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FLOWCONTROLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FLOWCONTROL_GLOBAL_H
